version: '3.8'

services:
  postgres:
    image: postgres
    container_name: online-library-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_backups:/backups
    env_file: .env
    expose:
      - 5432

  django:
    container_name: online-library-django
    build: ./backend
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
      - static_volume:/usr/src/static
      - media_volume:/usr/src/media
      - postgres_backups:/backups
      - logs:/usr/src/logs
    expose:
      - 8000
    env_file: .env
    depends_on:
      - postgres

  vue:
    container_name: online-library-vue
    build: ./frontend
    volumes:
      - frontend:/usr/src/frontend
    depends_on:
      - django

  nginx:
    container_name: online-library-nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/static
      - media_volume:/usr/src/media
      - frontend:/usr/src/frontend
    depends_on:
      - django
      - vue

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    container_name: online-library-pgbackups
    restart: always
    volumes:
      - postgres_backups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    env_file: .env

# Celery
  redis:
    image: redis
    container_name: online-library-redis
    restart: always

  celery-worker:
    container_name: online-library-celery-worker
    build:
      context: ./backend
    command: celery -A main worker --loglevel=info
    volumes:
      - ./backend:/usr/src/backend
      - media_volume:/usr/src/media
      - static_volume:/usr/src/static
      - logs:/usr/src/logs
      - postgres_backups:/backups
    env_file: .env
    links:
        - redis
    depends_on:
        - redis
    restart: always

  celery-beat:
    container_name: online-library-celery-beat
    build:
      context: ./backend
    command: celery -A main beat --loglevel=info
    volumes:
      - ./backend:/usr/src/backend
      - media_volume:/usr/src/media
      - static_volume:/usr/src/static
      - logs:/usr/src/logs
      - postgres_backups:/backups
    env_file: .env
    links:
        - redis
        - celery-worker
    depends_on:
        - redis
        - celery-worker
    restart: always

  flower:
    container_name: online-library-flower
    image: mher/flower
    env_file: .env
    ports:
      - "8888:8888"
    links:
      - redis
      - celery-worker
      - celery-beat
    depends_on:
      - redis
      - celery-worker
      - celery-beat

volumes:
  postgres_data:
  postgres_backups:
  static_volume:
  media_volume:
  logs:
  frontend: