# Generated by Django 4.1.2 on 2022-10-19 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/photos/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Фото'),
        ),
    ]
